@BaseURL=http://localhost:3000/api
@productId=04193b03-dca3-4ff0-b1d6-3ab2e6d63a8b

### Create a Product
POST {{BaseURL}}/products
Content-Type: application/json

{
    "name": "Coxinha de frango",
    "description": "salgado a base de frango e batata",
    "type": "SALTY",
    "image": "https://app.docemeu.com.br/wp-content/uploads/2022/11/coxinha-docemeu-lanchonete-campobelo-1.webp"
}
 

### Get All Products 
GET {{BaseURL}}/products


### Get a Products Details  
GET {{BaseURL}}/products/{{productId}}


### Update a Products Details  
PUT {{BaseURL}}/products/{{productId}}
Content-Type: application/json

{
    "name": "paçoca",
    "description": "amendoim",
    "type": "SALTY",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1bqdBjuY_83wdEzyFPCbrNkQnQBBMZHJSog&s"
}

### Delete a Products  
DELETE {{BaseURL}}/products/{{productId}}