@BaseURL=http://localhost:3000/api
@userId=4135a788-5217-4447-a2e4-f80ca659e0cd

### Create a User
POST {{BaseURL}}/users
Content-Type: application/json

{
    "name": "Luana",
    "email": "lua@vini.com",
    "password": "987654321",
    "cpf": "1198745632",
    "phone": "11965231458",
    "role":"SELLER"  
}


### Get All Users
GET {{BaseURL}}/users


### Get a User Details By ID
GET {{BaseURL}}/users/{{userId}}


### Update a User
PUT {{BaseURL}}/users/{{userId}}
Content-Type: application/json

{
    "email": "nero@vini.com",
    "cpf": "98745632125",
    "phone": "11952365471"
}

### Delete a User
DELETE {{BaseURL}}/users/{{userId}}
