@BaseURL=http://localhost:3000/api
@token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhN2MzOWQ1LWZhYzUtNDU5NS05NDdjLWQ2NjY3NzNmNWYyNCIsIm5hbWUiOiJWaW5pY2l1cyIsImVtYWlsIjoidmluaUB2aW5pLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcxNjc1MDQzNH0.Jj39AnXkCND7pKNNycmo-Ijt4TYnpME1Dn03lDkdZUE

### Authenticate an User
POST {{BaseURL}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"vini@vini.com",
    "password":"12345678"
}


### Teste
GET {{BaseURL}}/users HTTP/1.1
Authorization: "Bearer {{token}}"